### ISSUE TITLE
wrong extensionKind for remote session

### ISSUE THREAD

**Issue by david-morris** [sansarip/owlbear#114]
**Describe the bug**
All commands error out immediately after installing.
![image](https://github.com/sansarip/owlbear/assets/5530960/646c6da0-cc5e-4ec8-95f8-85bc1a2ee801)

**To Reproduce**
1. Install from extensions pane
2. run an owlbear command from the F1 menu

**Expected behavior**
Commands execute without error and perform edits

**Screenshots**

![image](https://github.com/sansarip/owlbear/assets/5530960/3a6a3717-1c70-4a13-bcb4-2c421fdc8746)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser none/electron
 - Version VSCode 1.84.2 Owlbear 1.1.5

**Additional context**

when I run a command from a keystroke, that errors out too:
![image](https://github.com/sansarip/owlbear/assets/5530960/36d479fa-5ab7-4de5-a4dc-3667ff6a737e)

I'm using a vscode remote setup with a WSL/Docker dev environment.

I refreshed the window but haven't done a cold start of vscode since installing.

**Comment by david-morris** [comment]
I've now been able to do more debugging on this.

Owlbear is working on the base Windows setup, but not when working in Remote Windows for WSL or in the dev container.

So that's an issue with either Remote Windows and Owlbear, or OS compatibility.

Maybe this is going to be something simple like setting whether this extension runs in the host or client of a remote session.

I'll test that when I can, but does anyone here already know whether Owlbear is compatible with Linux?

Edit: from https://github.com/sansarip/owlbear/issues/108 I take it that Owlbear is better tested Unix platforms than windows. I'm guessing that this is a problem with remote access, then.

[This extension development doc](https://code.visualstudio.com/api/advanced-topics/remote-extensions) will probably be useful on this ticket.

The first thing to try would be to [set the extension location in the package.json](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location) which lines up with my hunch that the wasm is getting loaded onto the wrong node interpreter.

![image](https://github.com/sansarip/owlbear/assets/5530960/88c268bd-a768-46aa-b2de-e7be265b7ee6)

**Comment by david-morris** [comment]
OK, I just used the `remote.extensionKind` setting to force the extension to run as a UI extension.  That worked, so this is probably a single line change to package.json.

**Comment by sansarip** [comment]
> OK, I just used the `remote.extensionKind` setting to force the extension to run as a UI extension.  That worked, so this is probably a single line change to package.json.

Thanks for the thoughtful investigation here David, and for putting up a fix! I'll take a look at your PR this evening (EST) 🤘
