### ISSUE TITLE
handle parsing error: JSX expressions must have one parent element

### ISSUE THREAD

**Issue by david-morris** [sansarip/owlbear#116]
**Is your feature request related to a problem? Please describe.**

One common use case I have is "I want to wrap this component." That doesn't work when I want to wrap the root of a JSX expression.

I would intuitively add a tag and match before, and then slurp the previous JSX expression single parent element.  However, this doesn't work at all in non-paredit mode, and it results in broken JSX in paredit mode.

**Describe the solution you'd like**

Owlbear should identify the two top-level JSX elements and slurping should work.

**Describe alternatives you've considered**

Alternatively, a new operation could wrap the current selection.  I would call it lower.  It should know when to add a fragment, when to add curly brackets, and when to add parentheses.

**Additional context**

I think what's happening has to do with Tree-sitter (reasonably) refusing to parse multi-parent JSX expressions.

Let's say we start with this (non-practical example):
![image](https://github.com/sansarip/owlbear/assets/5530960/71c0068d-4b32-4b4c-81d2-224989c62cfc)

What I want to do is have an easy way to end up here:
![image](https://github.com/sansarip/owlbear/assets/5530960/b10551ff-77a9-4821-834f-591a97bf0a5f)

**Comment by sansarip** [comment]
You've surmised the issue correctly; it's a parsing issue! I have to loosen the underlying JS grammar (see [this issue](https://github.com/users/sansarip/projects/2/views/1?pane=issue&itemId=4928182)), but that's easier said than done! Alternatively, I can add a new command to wrap selections, but then I'd be recreating [this existing extension](https://marketplace.visualstudio.com/items?itemName=bradgashler.htmltagwrap).

**Comment by david-morris** [comment]
For anyone else looking for a workaround, I think I'll try using that extension and then a macro extension like multi-command to set up one binding to select and wrap something.

**Comment by sansarip** [comment]
Would it be helpful if Owlbear included a command for selecting the current node? I.e. similar to what `Owlbear: Copy` does, but without copying to the clipboard

**Comment by david-morris** [comment]
Selecting the current node sounds great!  I don't know how to make that work with visual mode (I'm a former EviL/spacemacs user), but that seems broadly useful. For instance, it would be great for use with snippets.

Potentially that would allow owlbear to implement other quick-win features by leaning on the snippets API!

I have no idea what this _means_ for an extension like Owlbear, but I could see myself wanting to select the node, apply a snippet, and then clear the selection and have the cursor on some specific place for my "owlbear mode" (which is a VSpaceCode menu over normal mode) or wanting to select the node and enter visual mode, depending on what I'm doing.
