### ISSUE TITLE
JS objects break structural editing

### ISSUE THREAD

**Issue by david-morris** [sansarip/owlbear#117]
**Describe the bug**
Weird things happen inside objects. 
I tested both of these with paredit on and off and got the same results.

## Slurp Forward
1. initial state
```tsx
const foo = {
    newParent: { },
    originalParent: { originalChild: "bar" }
}
```
2. cursor:
![image](https://github.com/sansarip/owlbear/assets/5530960/1eff7b7e-3210-4231-8302-f31cd98ffaeb)

3. Owlbear: Slurp Forward

**Expected behavior**
```tsx
const foo = {
    newParent: { originalParent: { originalChild: "bar" }}
}
```
**Actual result**
No change:
```tsx
const foo = {
    newParent: { },
    originalParent: { originalChild: "bar" }
}
```

## Cut

1. initial state
```tsx
const foo = {
    newParent: { },
    originalParent: { originalChild: "bar" }
}
```
2. cursor
![image](https://github.com/sansarip/owlbear/assets/5530960/8e4452d6-9b82-43ee-9691-b9bc015eb2dd)

3. Owlbear cut

**Expected behavior**
![image](https://github.com/sansarip/owlbear/assets/5530960/cc432169-bfb4-4923-9b4a-ad21325095c7)

**Actual result**
![image](https://github.com/sansarip/owlbear/assets/5530960/55a89811-16af-45da-acd4-1c59bb039d7f)

**Comment by sansarip** [comment]
Slurping from within objects isn't supported ATM, but I can take a look at supporting this use case! Tracking it on the [project board](https://github.com/users/sansarip/projects/2/views/1)
