### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jdhuntington** [sansarip/owlbear#33]
Is this available in the vscode marketplace? If not, is it possible to install this extension without going through the development setup?

Happy to help with documenting/writing if that's all that's needed.

**Comment by sansarip** [comment]
Hello! 👋

Thanks for your interest! This tool is still very early stage, _heavily_ in development, and not yet released! Please keep a watchful eye 👁 on this repo as we make updates and work towards releasing on the VS Code marketplace 🚀
