### ISSUE TITLE
Support multi-language parsing

### ISSUE THREAD

**Issue by sansarip** [sansarip/owlbear#42]
Currently, the [main parse ns](https://github.com/sansarip/owlbear/blob/107badc67f2a3f0b54b0cb9b7e714f9acdd8ff4a/src/cljs/owlbear/html/parse.cljs) handles only the loading-in of one Tree-sitter-language wasm. The goal here is to expand the Owlbear parsing apparatus to support the loading of multiple language wasms so we can readily support Typescript, TSX, and potentially more languages!

**Comment by ctf0** [comment]
can this be expanded to support languages that have similar characteristics ex.`blade,bug,...` as `html`
